// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TvMaze.Data.OptimizedModel
{
    [DbContext(typeof(TvMazeDbContext))]
    public partial class TvMazeDbContextModel : RuntimeModel
    {
        static TvMazeDbContextModel()
        {
            var model = new TvMazeDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static TvMazeDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
